Tracardi/tracardi

tracardi/process_engine/action/v1/return_random_element_action.py
Tracardi random item plugin (#237)
Added plugin that returns random value from provided list of values.
----
=> Tracardi random item plugin (#237)

tracardi/service/event_validator.py
Validation fix (#334)
----fixed event validation bug, wrote new test for validation service
=> Validation fix (#334)

tracardi/process_engine/action/v1/switch_action.py
switch plugin (#335)
added switch plugin
=> switch plugin (#335)

tracardi/process_engine/action/v1/strings/regex_replace/model/config.py, tracardi/process_engine/action/v1/strings/regex_replace/plugin.py
regex replace plugin (#348)
Added regex replace plugin
----
=> regex replace plugin (#348)

tracardi/process_engine/action/v1/json_schema_validation_action.py, tracardi/service/event_validator.py
JSON schema validation plugin (#346)
----added JSON schema validation plugin
=> JSON schema validation plugin (#346)

tracardi/process_engine/action/v1/mapping_action.py
Mapping plugin case sensitive (#347)
----like in issue desc
=> Mapping plugin case sensitive (#347)

tracardi/process_engine/action/v1/ux/question_popup/plugin.py, tracardi/process_engine/action/v1/ux/snackbar/plugin.py
Question popup plugin (#364)
added plugin for question popup widget
=> Question popup plugin (#364)

tracardi/process_engine/action/v1/ux/rating_popup/plugin.py
rating widget plugin (#82)
added plugin for rating widget.
=> rating widget plugin (#82)

tracardi/process_engine/action/v1/connectors/mixpanel/client.py, tracardi/process_engine/action/v1/connectors/mixpanel/fetch_funnel/model/config.py, tracardi/process_engine/action/v1/connectors/mixpanel/fetch_funnel/plugin.py, tracardi/process_engine/action/v1/connectors/mixpanel/send/model/config.py, tracardi/process_engine/action/v1/connectors/mixpanel/send/plugin.py
mixpanel plugins (#330)
----Added mixpanel plugins for sending events and fetching funnels.
=> mixpanel plugins (#330)

tracardi/process_engine/action/v1/ux/consent/plugin.py
bugfix (#93)
----fixed bug by correcting a mistake in plugin init
=> bugfix (#93)

tracardi/service/login_service.py, tracardi/service/storage/drivers/elastic/user.py
user site (# 240, #74)
----added functionalities required for user management site
=> user site (# 240, #74)

tracardi/service/notation/dot_accessor.py
dot_accessor casting + tests (#375)
----added casting functionality to dot_accessor
=> dot_accessor casting + tests (#375)

tracardi/process_engine/action/v1/traits/condition_set/model/config.py, tracardi/process_engine/action/v1/traits/condition_set/plugin.py
Conditions set plugin (#376)
---- plugin, tests, manual
=> Conditions set plugin (#376)

tracardi/domain/destination.py
added documentation for API (#57)
----like in title
=> added documentation for API (#57)

README.md
Fixed a typo. "Intorduction" > "Introduction"
=> Update README.md, typo fixed

tracardi/process_engine/action/v1/strings/regex_match/plugin.py
plugin tests + bug fixes 
like in title
----
=> plugin tests + bug fixes 

tracardi/process_engine/action/v1/connectors/airtable/client.py, tracardi/process_engine/action/v1/connectors/airtable/fetch_records/model/config.py, tracardi/process_engine/action/v1/connectors/airtable/fetch_records/plugin.py, tracardi/process_engine/action/v1/connectors/airtable/send_record/model/config.py, tracardi/process_engine/action/v1/connectors/airtable/send_record/plugin.py
Airtable plugins (#89)
added Airtable plugins
----
=> Airtable plugins (#89)

tracardi/process_engine/action/v1/traits/assign_condition_result/model/config.py, tracardi/process_engine/action/v1/traits/assign_condition_result/plugin.py
assign condition result plugin (#377)
added assign condition result plugin
----
=> assign condition result plugin (#377)

tracardi/service/storage/drivers/elastic/tag.py
event tagging site requirements (#371)
added event taggin site
----
=> event tagger site requirements (#371)

tracardi/process_engine/action/v1/operations/reduce_array/model/config.py, tracardi/process_engine/action/v1/operations/reduce_array/plugin.py
reduce array plugin (#390)
----Added array-reducing plugin
=> reduce array plugin (#390)

tracardi/domain/resource.py, tracardi/process_engine/destination/mautic_connector.py, tracardi/service/resources.py
Pull request title with short description (#<issue-id>)
----added Mautic destination
=> Mautic destination

tracardi/service/storage/elastic_client.py
Redis and ES health check endpoints (#415)
added new endpoints
----
=> Redis and ES health check endpoints (#415)

tracardi/process_engine/action/v1/connectors/matomo/client.py, tracardi/process_engine/action/v1/connectors/matomo/send_event/model/config.py, tracardi/process_engine/action/v1/connectors/matomo/send_event/plugin.py, tracardi/process_engine/action/v1/connectors/matomo/send_event/service/page_performance.py, tracardi/service/resources.py, tracardi/service/storage/drivers/elastic/session.py
Matomo plugin
----added plugin for Matomo
=> Matomo plugin

tracardi/process_engine/action/v1/internal/get_prev_session/model/config.py, tracardi/process_engine/action/v1/internal/get_prev_session/plugin.py, tracardi/service/setup/setup_plugins.py, tracardi/service/storage/drivers/elastic/session.py
last session plugin (#417)
added plugin that finds nth last session for the current profile
----
=> Prev session plugin (#417)

tracardi/process_engine/action/v1/internal/get_prev_event/model/config.py, tracardi/process_engine/action/v1/internal/get_prev_event/plugin.py, tracardi/service/setup/setup_plugins.py, tracardi/service/storage/drivers/elastic/event.py
get previous event plugin (#416)
----
=> get previous event plugin (#416)

tracardi/service/storage/drivers/elastic/log.py
filtering logs (#422)
----added new function for filtering logs in driver
=> filtering logs (#422)

tracardi/service/storage/drivers/elastic/api_instance.py
dead instance removal (#426)
added removing dead instances functionality
----
=> dead instance removal (#426)

tracardi/service/storage/drivers/elastic/event.py
event source traffic details (#424)
----added driver functionalities required for this task
=> event source traffic details (#424)

tracardi/process_engine/tql/domain/field.py, tracardi/process_engine/tql/grammar/uql_expr.lark, tracardi/process_engine/tql/transformer/expr_transformer.py
parser fixes, added empty operator (#251, #407)
----fixed parser bugs, added new EMPTY/ NOT EMPTY functionality
=> parser fixes, added empty operator (#251, #407)

tracardi/process_engine/action/v1/operations/read_from_memory/model/config.py, tracardi/process_engine/action/v1/operations/read_from_memory/plugin.py, tracardi/process_engine/action/v1/operations/write_to_memory/model/config.py, tracardi/process_engine/action/v1/operations/write_to_memory/plugin.py, tracardi/service/setup/setup_plugins.py
memory plugins (#81)
----added memory plugins 
=> memory plugins (#81)

tracardi/process_engine/action/v1/consents/require_consents_action/model/config.py, tracardi/process_engine/action/v1/consents/require_consents_action/plugin.py, tracardi/service/setup/setup_plugins.py
Require consents plugin (#414)
----added plugin that checks for consents in profile data
=> Require consents plugin (#414)

tracardi/process_engine/action/v1/consents/add_consent_action/model/payload.py, tracardi/process_engine/action/v1/consents/add_consent_action/plugin.py, tracardi/process_engine/action/v1/consents/require_consents_action/plugin.py
Consent plugins fix
fixed consent system so that it's consistent
----
=> Consent plugins fix

tracardi/process_engine/action/v1/consents/add_consent_action/plugin.py, tracardi/process_engine/action/v1/consents/require_consents_action/plugin.py
ConsentRevoke implementation
----
=> ConsentRevoke implementation

tracardi/service/storage/drivers/elastic/api_instance.py
api instance removing bug fix
----added refresh method to driver
=> api instance removing bug fix

tracardi/process_engine/action/v1/connectors/civi_crm/add_contact/model/config.py, tracardi/process_engine/action/v1/connectors/civi_crm/add_contact/plugin.py, tracardi/process_engine/action/v1/connectors/civi_crm/client.py, tracardi/requirements.txt, tracardi/service/resources.py, tracardi/service/setup/setup_plugins.py
civicrm plugin v1 (#436)
----first draft version of civicrm plugin
=> civicrm plugin v1 (#436)

tracardi/process_engine/action/v1/connectors/slack/send_message/plugin.py
=> minor slack plugin fixes

tracardi/process_engine/action/v1/connectors/active_campaign/add_contact/model/config.py, tracardi/process_engine/action/v1/connectors/active_campaign/add_contact/plugin.py, tracardi/process_engine/action/v1/connectors/active_campaign/client.py, tracardi/process_engine/action/v1/connectors/active_campaign/fetch_by_email/model/config.py, tracardi/process_engine/action/v1/connectors/active_campaign/fetch_by_email/plugin.py, tracardi/service/resources.py, tracardi/service/setup/setup_plugins.py
active campaign plugins v1
added active campaign integration
----
=> active campaign plugins v1

tracardi/domain/event_source.py, tracardi/service/setup/mappings/event-source-index.json
returns_profile option implementation
Pull request description
----
=> returns_profile option implementation for event source

tracardi/domain/batch.py, tracardi/domain/task.py, tracardi/process_engine/batch/batch_runner.py, tracardi/process_engine/batch/mysql.py, tracardi/service/batches.py, tracardi/service/resources.py, tracardi/service/setup/mappings/batch-index.json, tracardi/service/setup/mappings/task-index.json, tracardi/service/storage/drivers/elastic/batch.py, tracardi/service/storage/drivers/elastic/task.py, tracardi/service/storage/drivers/elastic_driver.py, tracardi/service/storage/index.py
=> Batch imports

tracardi/process_engine/action/v1/connectors/active_campaign/add_contact/plugin.py, tracardi/process_engine/action/v1/connectors/active_campaign/client.py
active campaign fields fetching
----
=> active campaign fields fetching

tracardi/process_engine/action/v1/connectors/salesforce/marketing_cloud/client.py, tracardi/process_engine/action/v1/connectors/salesforce/marketing_cloud/send/model/config.py, tracardi/process_engine/action/v1/connectors/salesforce/marketing_cloud/send/plugin.py, tracardi/requirements.txt, tracardi/service/resources.py, tracardi/service/setup/setup_plugins.py
Marketing cloud data extension plugin
----
=> Marketing cloud data extension plugin

tracardi/process_engine/action/v1/connectors/matomo/send_event/model/config.py
=> matomo plugin quick fix

tracardi/process_engine/action/v1/internal/assign_profile_id/plugin.py, tracardi/process_engine/action/v1/log_action.py, tracardi/process_engine/action/v1/raise_error_action.py
docs for throw error, assign profile id and log message (#460)
----
=> docs for throw error, assign profile id and log message (#460)

tracardi/process_engine/import/mysql_query_importer.py, tracardi/service/setup/setup_import_types.py
mysql query import (#467)
----
=> mysql query import (#467)

tracardi/config.py
caching tokens on Redis (#483)
----
=> caching tokens on Redis (#483)

tracardi/service/setup/mappings/event-index.json
Move event properties to event payload and make properties as indexed (#481)
----
=> Move event properties to event payload and make properties as indexed

tracardi/service/setup/setup_indices.py, tracardi/service/storage/elastic_storage.py, tracardi/service/storage/index.py, tracardi/service/storage/indices_manager.py, tracardi/service/storage/persistence_service.py, tracardi/service/tracker.py
Pull request title with a short description (#501)
Refactoring of Index class
=> Refactored Index.

tracardi/service/storage/persistence_service.py
=> filtering bug fix (#512)

tracardi/domain/import_config.py, tracardi/process_engine/import/elastic_importer.py, tracardi/process_engine/import/mysql_importer.py, tracardi/process_engine/import/mysql_query_importer.py
Validators for imports (#506)
----user no longer can pass empty values 
=> Validators for imports (#506)

tracardi/process_engine/action/v1/events/event_discarder/plugin.py, tracardi/service/setup/setup_plugins.py
discard event plugin (#493)
----
=> discard event plugin (#493)

tracardi/domain/flow.py
flow enabling bug fix (#524)
----
=> flow enabling bug fix (#524)

tracardi/domain/flow.py, tracardi/process_engine/action/v1/flow/start/start_action.py, tracardi/service/wf/domain/flow_graph_data.py
nodes rearrangement (#488)
----
=> nodes rearrangement (#488)

tracardi/domain/flow.py, tracardi/domain/flow_meta_data.py, tracardi/process_engine/rules_engine.py, tracardi/service/setup/mappings/flow-index.json, tracardi/service/wf/domain/flow.py
flow enabling regression (#527)
----
=> flow enabling regression (#527)

tracardi/process_engine/action/v1/connectors/civi_crm/add_contact/plugin.py, tracardi/process_engine/action/v1/connectors/civi_crm/client.py, tracardi/process_engine/destination/civicrm_connector.py, tracardi/service/setup/setup_resources.py
=> civi destination (#466)

tracardi/process_engine/action/v1/memory/collect/model/config.py, tracardi/process_engine/action/v1/memory/collect/plugin.py, tracardi/process_engine/action/v1/traits/copy_trait_action.py, tracardi/service/setup/setup_plugins.py
Pull request title with short description (#541)
- [ x] Give the same name to the pull request as the name of ticket 
=> PayloadMemoryCollector plugin

tracardi/service/plugin/domain/console.py, tracardi/service/wf/domain/debug_call_info.py, tracardi/service/wf/domain/debug_info.py, tracardi/service/wf/domain/graph_invoker.py
=> 545 show error icon on node when there is an error in consolelog

tracardi/process_engine/action/v1/traits/field_type_action.py, tracardi/service/setup/setup_plugins.py
added field info plugin (#539)
----
=> Plugin "type of field"  (#539)

tracardi/domain/migration_payload.py, tracardi/process_engine/migration/migration_manager.py
minor migration bug fixes, minor improvements (#181)
----
=> minor migration bug fixes, minor improvements (#181)

tracardi/process_engine/migration/migration_manager.py, tracardi/service/setup/mappings/task-index.json
=> Task management fix

tracardi/process_engine/action/v1/traits/append_trait_action.py
added missing plugin docs (#538, #521)
=> added missing plugin docs (#538, #521)

tracardi/process_engine/action/v1/connectors/mysql/query/plugin.py
allow duplicates param on ListOfDottedInputs (#564)
Pull request description
----
=> allow duplicates param on ListOfDottedInputs (#564)

tracardi/domain/version.py, tracardi/process_engine/migration/migration_manager.py, tracardi/service/storage/drivers/elastic/version.py
warning when re-doing migration for same version
=> warning when re-doing migration for same version

tracardi/domain/user.py, tracardi/service/setup/mappings/user-index.json, tracardi/service/storage/drivers/elastic/user.py
user account expiration date (#523)
----
=> user account expiration date (#523)

tracardi/process_engine/action/v1/flow/start/start_action.py
start action event props bug fix (#580)
=> start action event props bug fix (#580)

tracardi/process_engine/migration/schemas/test.json
added worker for moving user index (#566)
=> added worker for moving user index (#566)

tracardi/process_engine/action/v1/internal/add_empty_profile/plugin.py, tracardi/process_engine/action/v1/traits/hash_traits_action.py, tracardi/process_engine/action/v1/traits/mask_traits_action.py, tracardi/service/plugin/runner.py, tracardi/service/plugin/service/plugin_runner.py
=> Mask and Hash traits fix + tests (#531)

tracardi/service/setup/mappings/event-management-index.json
added tags to index mapping
----
=> added tags to index mapping

tracardi/process_engine/migration/schemas/070_to_071.json
=> refactoring + bug fixes

tracardi/service/setup/mappings/api-instance-index.json, tracardi/service/setup/mappings/consent-type.json, tracardi/service/setup/mappings/console-log-index.json, tracardi/service/setup/mappings/debug-info-index.json, tracardi/service/setup/mappings/default-dynamic-index.json, tracardi/service/setup/mappings/destination-index.json, tracardi/service/setup/mappings/event-index.json, tracardi/service/setup/mappings/event-management-index.json, tracardi/service/setup/mappings/event-source-index.json, tracardi/service/setup/mappings/flow-index.json, tracardi/service/setup/mappings/import-index.json, tracardi/service/setup/mappings/log-index.json, tracardi/service/setup/mappings/plugin-index.json, tracardi/service/setup/mappings/profile-index.json, tracardi/service/setup/mappings/resource-index.json, tracardi/service/setup/mappings/rule-index.json, tracardi/service/setup/mappings/schedule-index.json, tracardi/service/setup/mappings/segment-index.json, tracardi/service/setup/mappings/session-index.json, tracardi/service/setup/mappings/tag-index.json, tracardi/service/setup/mappings/task-index.json, tracardi/service/setup/mappings/tracardi-pro-index.json, tracardi/service/setup/mappings/user-index.json, tracardi/service/setup/mappings/user-log-index.json, tracardi/service/setup/mappings/value-threshold-index.json, tracardi/service/setup/mappings/version-index.json, tracardi/service/storage/indices_manager.py
=> mappings fix (#598)

tracardi/service/generic_http_client.py
generic HTTP client implementation (#602)
=> generic HTTP client implementation (#602)

tracardi/process_engine/action/v1/ux/generic/plugin.py, tracardi/service/setup/setup_plugins.py
=> generic UIX plugin

tracardi/process_engine/action/v1/password_generator_action.py, tracardi/process_engine/action/v1/ux/generic/plugin.py, tracardi/service/setup/setup_plugins.py
Pull request title with short description (#607)
=> 607 password generator

tracardi/process_engine/action/v1/events/event_aggregator/model/configuration.py, tracardi/process_engine/action/v1/events/event_aggregator/plugin.py
=> Make JSON FORM field with available frields from event index (#139)

tracardi/process_engine/action/v1/connectors/mailchimp/transactional_email/plugin.py
=> mailchimp plugin fix (#615)

tracardi/process_engine/action/v1/connectors/elasticsearch/query/model/config.py, tracardi/process_engine/action/v1/connectors/elasticsearch/query/plugin.py
added autoload for elasticsearch query plugin (#618)
=> added autoload for elasticsearch query plugin (#618)

tracardi/process_engine/action/v1/connectors/elasticsearch/query/model/config.py, tracardi/process_engine/action/v1/connectors/elasticsearch/query/plugin.py, tracardi/service/storage/elastic_client.py
Use select with indices in ES plugin (#618)
Replaced AsyncElasticsearch with our client, fixed the bug with credentials.
=> Use select with indices in ES plugin (#618)

tracardi/domain/resource_type.py, tracardi/service/setup/setup_resources.py
resource type refactoring + documenting resources (#510)
=> resource type refactoring + documenting resources (#510)

tracardi/domain/report.py, tracardi/domain/storage_result.py, tracardi/process_engine/action/v1/internal/entity/delete/plugin.py, tracardi/process_engine/action/v1/internal/entity/load/plugin.py, tracardi/process_engine/action/v1/internal/get_report/model/config.py, tracardi/process_engine/action/v1/internal/get_report/plugin.py, tracardi/service/report_manager.py, tracardi/service/setup/mappings/report-index.json, tracardi/service/setup/setup_plugins.py, tracardi/service/storage/drivers/elastic/report.py, tracardi/service/storage/drivers/elastic_driver.py, tracardi/service/storage/index.py
=> Report server (#630)

tracardi/process_engine/action/v1/notification_plugin_action.py, tracardi/service/setup/setup_plugins.py
Type pull request title with short description (#<617>)
Add novu trigger plugin
=> 617 novu plugin action

tracardi/process_engine/action/v1/connectors/matomo/send_event/plugin.py
=> matomo bug fix

tracardi/process_engine/action/v1/weekdays_checker_action.py, tracardi/service/setup/setup_plugins.py
Type pull request title with short description (#608 )
add plugin which check whether is weekend day or not and register it in setup_plugins.py
=> 608 plugin weekdays

tracardi/process_engine/action/v1/starts_with_action.py, tracardi/service/setup/setup_plugins.py
Type pull request title with short description (#645)
645 plugin startswith 
added startswith plugin and registered it
=> 645 plugin startswith

tracardi/process_engine/action/v1/ends_with_action.py, tracardi/service/setup/setup_plugins.py
Type pull request title with short description (#644 )
644 plugin endswith
----
=> 644 plugin endswith

tracardi/process_engine/action/v1/flow/start/model/configuration.py
Type pull request title with short description (#642 )
Trim EventID on Start node #642
created 2 validators for event_type.id and even_id to trim leading whitespaces
----
=> Trim EventID on Start node #642

tracardi/domain/storage_record.py
----Fix the broken Data layer isolation (#649)
=> Fix the broken Data layer isolation (#649)

tracardi/process_engine/action/v1/contains_string_action.py, tracardi/service/setup/setup_plugins.py
Type pull request title with short description (#646 )
646 field contains string
add contains string plugin and register it
----
=> 646 field contains string

tracardi/process_engine/tql/domain/missing_value.py, tracardi/process_engine/tql/grammar/uql_expr.lark, tracardi/process_engine/tql/transformer/expr_transformer.py
Add CONTAINS and STARTS_WTH and ENDS_WITH to IF plugin[#643](https://github.com/Tracardi/tracardi/issues/643)
---- fixes #643 
=> Add CONTAINS and STARTS_WTH and ENDS_WITH to IF plugin#643

tracardi/domain/event.py, tracardi/domain/event_payload_validator.py, tracardi/service/event_props_reshaper.py, tracardi/service/event_validator.py, tracardi/service/setup/mappings/event-management-index.json, tracardi/service/tracker.py
=> Event props reshaping

tracardi/process_engine/action/v1/connectors/api_call/plugin.py, tracardi/service/setup/setup_resources.py, tracardi/service/url_constructor.py
https://github.com/Tracardi/tracardi/issues/681
this allows you to add proxy next to the url in resources. The proxy should be a full url version
http://your_user:your_password@your_proxy_url:your_proxy_port
----
=> New feature: httpclient proxy

test/unit/test_event_props_reshaper.py, tracardi/domain/event_payload_validator.py, tracardi/service/event_manager_cache.py, tracardi/service/event_props_reshaper.py, tracardi/service/event_validator.py, tracardi/service/notation/dict_traverser.py, tracardi/service/tracker.py
----Event reshaping is not working properly[#678](https://github.com/Tracardi/tracardi/issues/678)
=> Event reshaping is not working properly#678

tracardi/service/setup/setup_resources.py
----Missing mautic resource documentation[#689](https://github.com/Tracardi/tracardi/issues/689)
=> Missing mautic resource documentation#689

tracardi/service/setup/setup_resources.py
----Missing Civi CRM resource documentation[#687](https://github.com/Tracardi/tracardi/issues/687)
=> Missing Civi CRM resource documentation#687

tracardi/domain/storage_record.py, tracardi/service/report_manager.py
----report aggregation handling bug fix
=> report aggregation handling bug fix

tracardi/config.py, tracardi/process_engine/migration/migration_manager.py, tracardi/process_engine/migration/schemas/071_to_072.json
----Create migration script to version 0.7.2 (#558)
=> Create migration script to version 0.7.2 (#558)

tracardi/service/tracker.py
----[Event should be saved even if it does not pass validation#686](https://github.com/Tracardi/tracardi/issues/686)
=> Event should be saved even if it does not pass validation#686

README.md
=> update docs to include redis requirement

test/unit/plugins/test_plugin_string_join.py, tracardi/process_engine/action/v1/strings/string_join/model/configuration.py, tracardi/process_engine/action/v1/strings/string_join/plugin.py, tracardi/service/setup/setup_plugins.py
Create plugin that joins strings #726
added plugin code and test code 
----
=> Create plugin that joins strings #726

test/unit/plugins/test_plugin_sort_dictionary.py, tracardi/process_engine/action/v1/sort_dictionary.py, tracardi/service/setup/setup_plugins.py
Create plugin that sorts a referenced dictionary #733
Added the plugin and the test.
----
=> Create plugin that sorts a referenced dictionary #733

tracardi/domain/resources/twitter_resrouce.py, tracardi/process_engine/action/v1/connectors/twitter/tweet/model/config.py, tracardi/process_engine/action/v1/connectors/twitter/tweet/plugin.py, tracardi/service/setup/setup_plugins.py, tracardi/service/setup/setup_resources.py
issues list twiter plugins that tweets a message build form text template (#729 )
----
add, register plugin
add config for plugin
add documentation for resource to twitter plugin
=> 729 issues list twiter plugins that tweets a message build form text template

tracardi/process_engine/action/v1/ux/intercom/plugin.py, tracardi/service/setup/setup_plugins.py
Type pull request title with short description (#746 Intercom plugin)
added plugin and registered it
----
=> intercom plugin

CONTRIBUTING.md, tracardi/domain/payload/tracker_payload.py, tracardi/domain/profile.py, tracardi/process_engine/action/v1/connectors/mysql/query/plugin.py, tracardi/process_engine/action/v1/microservice/plugin.py, tracardi/process_engine/action/v1/operations/read_from_memory/plugin.py, tracardi/process_engine/action/v1/password_generator_action.py, tracardi/process_engine/action/v1/strings/string_validator/service/validator.py, tracardi/process_engine/action/v1/ux/_rating_popup/plugin.py, tracardi/process_engine/tql/transformer/filter_transformer.py, tracardi/service/postpone_call.py, tracardi/service/setup/setup_indices.py, tracardi/service/storage/drivers/elastic/log.py, tracardi/service/storage/drivers/elastic/session.py, tracardi/service/wf/domain/flow_graph_data.py, tracardi/service/wf/domain/graph_invoker.py
This PR fixes several typos and grammar mistakes in:
* `CONTRIBUTING.md`
* Code files
I don't think this warrants a separate GitHub issue.
----
=> Typo fixes

tracardi/process_engine/action/v1/sort_action.py, tracardi/service/setup/setup_plugins.py
Type pull request title with short description (#732)
----
=> Added array sorting pluign

tracardi/domain/resources/google_analytics_id.py, tracardi/process_engine/action/v1/connectors/google/analytics/model/configuration.py, tracardi/process_engine/action/v1/connectors/google/analytics/plugin.py, tracardi/process_engine/action/v1/connectors/google/analytics/registry.py, tracardi/service/setup/setup_plugins.py, tracardi/service/setup/setup_resources.py
Type pull request title with short description (#56 )
Google analytics event tracker plugin
----
If your pull request is about ~20 lines of code add license information in your code in form of comment. i.e. # License: MIT, Author:  Mateusz Zitaruk
=> google analytics tracker plugin

tracardi/domain/resources/google_analytics_v4.py, tracardi/process_engine/action/v1/connectors/google/analytics_v4/models/configuration.py, tracardi/process_engine/action/v1/connectors/google/analytics_v4/plugin.py, tracardi/process_engine/action/v1/connectors/google/analytics_v4/registry.py, tracardi/service/setup/setup_plugins.py, tracardi/service/setup/setup_resources.py
Type pull request title with short description (#774 google analytics tracker plugin)
----
=> google analytics 4 tracker plugin

tracardi/domain/resources/github.py, tracardi/process_engine/action/v1/connectors/github/forms/GitHubFormFields.py, tracardi/process_engine/action/v1/connectors/github/github_client.py, tracardi/process_engine/action/v1/connectors/github/issues/get/plugin.py, tracardi/process_engine/action/v1/connectors/github/issues/list/plugin.py, tracardi/process_engine/action/v1/connectors/github/model/config.py, tracardi/service/setup/setup_plugins.py, tracardi/service/setup/setup_resources.py
The initial implementation of 2 plugins and a GitHub API client to query the list of issues for a repository or to fetch the details for a single issue.
Relates to #712 
----
=>  Github client #712 
